using DadsEnergyReporter.Data;
using FluentAssertions;
using MimeKit;
using NodaTime;
using Xunit;

namespace DadsEnergyReporter.Service
{
    public class ReportFormatterTest
    {
        private readonly ReportFormatterImpl reportFormatter = new ReportFormatterImpl();

        [Fact]
        public void PurchasedFromOru()
        {
            var report = new SolarAndUtilityReport(new DateInterval(new LocalDate(2017, 07, 17), new LocalDate(2017, 08, 16)), 1234.56789, 9999,
                6780);
            MimeMessage actual = reportFormatter.FormatReport(report);
            actual.Subject.Should().Be("Electricity Usage Report for 7/17–8/16");
            actual.TextBody.Should().Be(@"Generated by solar panels: 1,235 kWh
Purchased from O&R: 9,999 kWh for $67.80
---
Total energy consumed: 11,234 kWh");
            actual.HtmlBody.Should().Be(@"<table style=""border-collapse: collapse"">
    <tr><td><b>Generated by solar panels:</b></td><td style=""text-align: right"">1,235 kWh</td><td></td></tr>
    <tr><td><b>Purchased from O&amp;R:</b></td><td style=""text-align: right"">9,999 kWh</td><td> for $67.80</td></tr>
    <tr style=""border-top: 1px solid black""><td><b>Total energy consumed:</b></td><td style=""text-align: right"">11,234 kWh</td><td></td></tr>
</table>");
        }

        [Fact]
        public void SoldToOru()
        {
            var report = new SolarAndUtilityReport(new DateInterval(new LocalDate(2017, 07, 17), new LocalDate(2017, 08, 16)), 1400, -400,
                20);
            MimeMessage actual = reportFormatter.FormatReport(report);
            actual.Subject.Should().Be("Electricity Usage Report for 7/17–8/16");
            actual.TextBody.Should().Be(@"Generated by solar panels: 1,400 kWh
Sold to O&R: 400 kWh
---
Total energy consumed: 1,000 kWh");
            actual.HtmlBody.Should().Be(@"<table style=""border-collapse: collapse"">
    <tr><td><b>Generated by solar panels:</b></td><td style=""text-align: right"">1,400 kWh</td><td></td></tr>
    <tr><td><b>Sold to O&amp;R:</b></td><td style=""text-align: right"">400 kWh</td><td></td></tr>
    <tr style=""border-top: 1px solid black""><td><b>Total energy consumed:</b></td><td style=""text-align: right"">1,000 kWh</td><td></td></tr>
</table>");
        }

        [Fact]
        public void Zeroes()
        {
            var report = new SolarAndUtilityReport(new DateInterval(new LocalDate(2017, 11, 1), new LocalDate(2017, 12, 2)), 0, 0, 2000);
            MimeMessage actual = reportFormatter.FormatReport(report);
            actual.Subject.Should().Be("Electricity Usage Report for 11/1–12/2");
            actual.TextBody.Should().Be(@"Generated by solar panels: 0 kWh
Purchased from O&R: 0 kWh for $20.00
---
Total energy consumed: 0 kWh");
            actual.HtmlBody.Should().Be(@"<table style=""border-collapse: collapse"">
    <tr><td><b>Generated by solar panels:</b></td><td style=""text-align: right"">0 kWh</td><td></td></tr>
    <tr><td><b>Purchased from O&amp;R:</b></td><td style=""text-align: right"">0 kWh</td><td> for $20.00</td></tr>
    <tr style=""border-top: 1px solid black""><td><b>Total energy consumed:</b></td><td style=""text-align: right"">0 kWh</td><td></td></tr>
</table>");
        }
    }
}